import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from './Login.module.scss'
import global from 'config/global'
import Header from 'components/Header'
import LoginForm from 'containers/LoginForm'
import SocialMedia from 'containers/socialMedia'

const inter = Inter({ subsets: ['latin'] })

export default function Login() {
  return (
    <>
      <Head>
        <title>{global.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className />
      <main className={styles.main}>
        <div className={styles.login}>
          <h1 className={styles.loginTitle}>Login</h1>
          <LoginForm />
          <div className={styles.forgotPassword}>
            <span>Forgot Password</span>
          </div>
          <SocialMedia />
        </div>
      </main>
    </>
  )
}
